name: enviar emails semanais

on:
  workflow_dispatch:

jobs:
  enviar_emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq msmtp
      
      - name: Check if json file exist
        run: |
          if [ ! -f "projects.json" ]; then
            echo "File not found: projects.json"
            exit 1
          fi
      
      - name: Send emails
        env:
          OUTLOOK_APP_PASSWORD: ${{ secrets.OUTLOOK_APP_PASSWORD }}
        run: |
            bash send_mail.sh