name: enviar emails semanais

on:
  workflow_dispatch:

jobs:
  enviar_emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq msmtp

      - name: Copy JSON file to work directory
        run: |
          echo "$PROJECTS_JSON" > projects.json

      - name: Send emails
        run: |
          bash send_mail.sh
